/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OrgaStandaloneSetup extends OrgaStandaloneSetupGenerated {

	public static void doSetup() {
		new OrgaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
