/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import swa.dsl.courses.parser.antlr.internal.InternalOrgaParser;
import swa.dsl.courses.services.OrgaGrammarAccess;

public class OrgaParser extends AbstractAntlrParser {

	@Inject
	private OrgaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOrgaParser createParser(XtextTokenStream stream) {
		return new InternalOrgaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OrgaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OrgaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
