/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OrgaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("swa/dsl/courses/parser/antlr/internal/InternalOrga.tokens");
	}
}
