/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OrgaUiModule extends AbstractOrgaUiModule {

	public OrgaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
