/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOrgaScopeProvider extends DelegatingScopeProvider {
}
