/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import swa.dsl.courses.ui.internal.CoursesActivator;

public class OrgaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CoursesActivator.getInstance().getInjector("swa.dsl.courses.Orga");
	}

}
