/**
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.orga;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see swa.dsl.courses.orga.OrgaFactory
 * @model kind="package"
 * @generated
 */
public interface OrgaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "orga";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.dsl.swa/courses/Orga";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "orga";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OrgaPackage eINSTANCE = swa.dsl.courses.orga.impl.OrgaPackageImpl.init();

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.ModelImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.DeclarationImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Audience</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__AUDIENCE = 0;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.CourseImpl <em>Course</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.CourseImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getCourse()
   * @generated
   */
  int COURSE = 2;

  /**
   * The feature id for the '<em><b>Audience</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__AUDIENCE = DECLARATION__AUDIENCE;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TITLE = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Department</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__DEPARTMENT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TYPE = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Course cat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__COURSE_CAT = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Teachers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TEACHERS = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Students</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__STUDENTS = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Course</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.TeacherImpl <em>Teacher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.TeacherImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getTeacher()
   * @generated
   */
  int TEACHER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEACHER__NAME = 0;

  /**
   * The number of structural features of the '<em>Teacher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEACHER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.StudentImpl <em>Student</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.StudentImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getStudent()
   * @generated
   */
  int STUDENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Student</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link swa.dsl.courses.orga.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see swa.dsl.courses.orga.impl.RoomImpl
   * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 5;

  /**
   * The feature id for the '<em><b>Audience</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__AUDIENCE = DECLARATION__AUDIENCE;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__LOCATION = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see swa.dsl.courses.orga.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link swa.dsl.courses.orga.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see swa.dsl.courses.orga.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see swa.dsl.courses.orga.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Declaration#getAudience <em>Audience</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Audience</em>'.
   * @see swa.dsl.courses.orga.Declaration#getAudience()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Audience();

  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Course <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course</em>'.
   * @see swa.dsl.courses.orga.Course
   * @generated
   */
  EClass getCourse();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Course#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see swa.dsl.courses.orga.Course#getTitle()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Title();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Course#getDepartment <em>Department</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Department</em>'.
   * @see swa.dsl.courses.orga.Course#getDepartment()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Department();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Course#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see swa.dsl.courses.orga.Course#getType()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Type();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Course#getCourse_cat <em>Course cat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Course cat</em>'.
   * @see swa.dsl.courses.orga.Course#getCourse_cat()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Course_cat();

  /**
   * Returns the meta object for the containment reference list '{@link swa.dsl.courses.orga.Course#getTeachers <em>Teachers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Teachers</em>'.
   * @see swa.dsl.courses.orga.Course#getTeachers()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Teachers();

  /**
   * Returns the meta object for the containment reference list '{@link swa.dsl.courses.orga.Course#getStudents <em>Students</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Students</em>'.
   * @see swa.dsl.courses.orga.Course#getStudents()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Students();

  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Teacher <em>Teacher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Teacher</em>'.
   * @see swa.dsl.courses.orga.Teacher
   * @generated
   */
  EClass getTeacher();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Teacher#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see swa.dsl.courses.orga.Teacher#getName()
   * @see #getTeacher()
   * @generated
   */
  EAttribute getTeacher_Name();

  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Student <em>Student</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Student</em>'.
   * @see swa.dsl.courses.orga.Student
   * @generated
   */
  EClass getStudent();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Student#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see swa.dsl.courses.orga.Student#getName()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_Name();

  /**
   * Returns the meta object for class '{@link swa.dsl.courses.orga.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see swa.dsl.courses.orga.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link swa.dsl.courses.orga.Room#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see swa.dsl.courses.orga.Room#getLocation()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Location();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OrgaFactory getOrgaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.ModelImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.DeclarationImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Audience</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__AUDIENCE = eINSTANCE.getDeclaration_Audience();

    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.CourseImpl <em>Course</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.CourseImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getCourse()
     * @generated
     */
    EClass COURSE = eINSTANCE.getCourse();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__TITLE = eINSTANCE.getCourse_Title();

    /**
     * The meta object literal for the '<em><b>Department</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__DEPARTMENT = eINSTANCE.getCourse_Department();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__TYPE = eINSTANCE.getCourse_Type();

    /**
     * The meta object literal for the '<em><b>Course cat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__COURSE_CAT = eINSTANCE.getCourse_Course_cat();

    /**
     * The meta object literal for the '<em><b>Teachers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__TEACHERS = eINSTANCE.getCourse_Teachers();

    /**
     * The meta object literal for the '<em><b>Students</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__STUDENTS = eINSTANCE.getCourse_Students();

    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.TeacherImpl <em>Teacher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.TeacherImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getTeacher()
     * @generated
     */
    EClass TEACHER = eINSTANCE.getTeacher();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEACHER__NAME = eINSTANCE.getTeacher_Name();

    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.StudentImpl <em>Student</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.StudentImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getStudent()
     * @generated
     */
    EClass STUDENT = eINSTANCE.getStudent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__NAME = eINSTANCE.getStudent_Name();

    /**
     * The meta object literal for the '{@link swa.dsl.courses.orga.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see swa.dsl.courses.orga.impl.RoomImpl
     * @see swa.dsl.courses.orga.impl.OrgaPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__LOCATION = eINSTANCE.getRoom_Location();

  }

} //OrgaPackage
