/*
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOrgaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(swa.dsl.courses.orga.OrgaPackage.eINSTANCE);
		return result;
	}
}
