/**
 * generated by Xtext 2.32.0
 */
package swa.dsl.courses.orga.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import swa.dsl.courses.orga.AudienceSize;
import swa.dsl.courses.orga.Declaration;
import swa.dsl.courses.orga.OrgaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link swa.dsl.courses.orga.impl.DeclarationImpl#getAudience <em>Audience</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeclarationImpl extends MinimalEObjectImpl.Container implements Declaration
{
  /**
   * The default value of the '{@link #getAudience() <em>Audience</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAudience()
   * @generated
   * @ordered
   */
  protected static final AudienceSize AUDIENCE_EDEFAULT = AudienceSize.SMALL;

  /**
   * The cached value of the '{@link #getAudience() <em>Audience</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAudience()
   * @generated
   * @ordered
   */
  protected AudienceSize audience = AUDIENCE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OrgaPackage.Literals.DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AudienceSize getAudience()
  {
    return audience;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAudience(AudienceSize newAudience)
  {
    AudienceSize oldAudience = audience;
    audience = newAudience == null ? AUDIENCE_EDEFAULT : newAudience;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OrgaPackage.DECLARATION__AUDIENCE, oldAudience, audience));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OrgaPackage.DECLARATION__AUDIENCE:
        return getAudience();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OrgaPackage.DECLARATION__AUDIENCE:
        setAudience((AudienceSize)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OrgaPackage.DECLARATION__AUDIENCE:
        setAudience(AUDIENCE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OrgaPackage.DECLARATION__AUDIENCE:
        return audience != AUDIENCE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (audience: ");
    result.append(audience);
    result.append(')');
    return result.toString();
  }

} //DeclarationImpl
